import Head from 'next/head';
import ProcessForm from '../components/ProcessForm';

export default function Home() {
  return (
    <>
      <Head>
        <title>Test SAAS 1754600369283</title>
        <meta name="description" content="A test SAAS generated by AutoSaaS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="min-h-screen bg-gray-50">
        {/* Hero Section */}
        <div className="bg-gradient-to-br from-blue-50 to-indigo-100 py-20">
          <div className="max-w-4xl mx-auto px-4 text-center">
            <h1 className="text-5xl font-bold text-gray-900 mb-6">
              Test SAAS 1754600369283
            </h1>
            <p className="text-xl text-gray-600 mb-8">
              A test SAAS generated by AutoSaaS
            </p>
          </div>
        </div>

        {/* Process Form Section */}
        <div className="py-20">
          <div className="max-w-2xl mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold text-gray-900 mb-4">
                Try It Now
              </h2>
              <p className="text-gray-600">
                Submit your information and see the magic happen
              </p>
            </div>
            
            <ProcessForm />
          </div>
        </div>
      </div>
    </>
  );
}